name: proxy-test

services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy-test
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      ECOMMERCEAPP_DOMAIN: ${ECOMMERCEAPP_DOMAIN}
      PORTFOLIOAPP_DOMAIN: ${PORTFOLIOAPP_DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data_test:/data
      - caddy_config_test:/config
    networks:
      - proxy

volumes:
  caddy_data_test:
  caddy_config_test:

networks:
  proxy:
    external: true
