name: proxy-test

services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy-test
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data_test:/data
      - caddy_config_test:/config
    networks:
      - proxy

volumes:
  caddy_data_test:
  caddy_config_test:

networks:
  proxy:
    external: true
